CREATE TABLE IF NOT EXISTS parametros (
    id INT AUTO_INCREMENT PRIMARY KEY,
    chave VARCHAR(100) NOT NULL UNIQUE,
    valor TEXT NOT NULL,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO parametros (chave, valor) VALUES
('PAT_ORIGEM', ''),
('PAT_DESTINO', ''),
('ORIGEM_URL', ''),
('DESTINO_URL', ''),
('PROJETO_DESTINO', ''),
('ITERATION_PATH', ''),
('ATIVIDADE_TASK', ''),
('RESPONSAVEL_TASK', '');
